apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "temperature-proxy-api.fullname" . }}-config
  labels:
    {{- include "temperature-proxy-api.labels" . | nindent 4 }}
data:
  WEATHER_BASE_URL: {{ .Values.config.weatherBaseUrl | quote }}
  WEATHER_TIMEOUT_MS: {{ .Values.config.weatherTimeoutMs | quote }}
  WEATHER_CACHE_TTL_SECONDS: {{ .Values.config.weatherCacheTtlSeconds | quote }}
  WEATHER_CACHE_MAX_SIZE: {{ .Values.config.weatherCacheMaxSize | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelEndpoint | quote }}
