apiVersion: v1
kind: ConfigMap
metadata:
  name: temperature-proxy-api-config
  labels:
    app: temperature-proxy-api
data:
  WEATHER_BASE_URL: "https://api.open-meteo.com"
  WEATHER_TIMEOUT_MS: "1000"
  WEATHER_CACHE_TTL_SECONDS: "60"
  WEATHER_CACHE_MAX_SIZE: "1000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318/v1/traces"
